### ISSUE TITLE
Show unversioned files in commit box works backwards

### ISSUE THREAD

**Issue by tgharold** [rabbitvcs/rabbitvcs#126]
In the RabbitVCS (0.16-1) commit box (SVN client), there is a "Show unversioned files" which hides the unversioned files when it is checked.  Which is backwards from what it should be doing.

![image](https://cloud.githubusercontent.com/assets/4880437/11301526/e181b6e6-8f65-11e5-92f5-26b2967a8560.png)

**Comment by tamcy** [comment]
Hi, I also see this problem with Git client. The problem seems to be that, the dialog always defaults to **not** showing unversioned files when it is opened, and toggling the checkbox changes this behavior (no matter the toggled state is on or off). However, the "show unversioned files" state is remembered and restored when the dialog opens. So, the dialog behaves correctly when the last remembered state of "show unversioned files" is unchecked. Otherwise, the behavior is opposite to what it is intended.

**Comment by dharasty** [comment]
Agree -- I'm seeing this bug too.  Note I think it only occurs if you leave "Show u files" checked when you close the window. It's as if the GUI remembers it is checked, but the app always assumes it was unchecked... then acts on the *toggle* rather than the actual current state.

**Comment by Fordi** [comment]
Went to fix this (as it annoys the hell out of me in my regular job) - and it looks like it's been fixed without comment.  

Current hash (58b887337a64dacdee1067df261896ac9c19235c) appears to handle the unversioned files toggle correctly.  

To test, please clone the latest from this repository, and install with `python setup.py install` (optionally with  `--install-layout=deb` if your in a debian/ubuntu flavor), and close.

**Comment by Fordi** [comment]
Relevant commit was explicitly for this: https://github.com/rabbitvcs/rabbitvcs/commit/c4ac1ce80bd0ab0bf6adabbcc21d63165879b76f

**Comment by kwill** [comment]
Related merge: https://github.com/rabbitvcs/rabbitvcs/pull/71
