### ISSUE TITLE
Unsupported locale setting when trying to display Git logs.

### ISSUE THREAD

**Issue by mavidser** [rabbitvcs/rabbitvcs#37]
Problem was marked as fixed some time ago, but still shows up for me. Current locale = en_IN

**Comment by bhuvanrawal** [comment]
This occurs because your locale is not supported. mine was en_IN 
To fix it Please Try these steps:
$ vi ~/.bashrc

export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

save and close
$ source ~/.bashrc

close nautilus
$ nautilus -q
Start nautilus again
$ nautilus

You should be able to read logs now!
Cheers!
