### ISSUE TITLE
Integration with Caja 1.8.1 on linux mint 17

### ISSUE THREAD

**Issue by fnkbz** [rabbitvcs/rabbitvcs#51]
I tried with these commands to make the rabbitvcs compatible with caja 1.8.1 but no luck. Any help?

sudo add-apt-repository ppa:rabbitvcs/ppa
sudo apt-get update
sudo apt-get install rabbitvcs-core

sudo cp ~/Downloads/cajacontextmenu*.py /usr/lib/pymodules/python2.7/rabbitvcs/util/
sudo python -m compileall /usr/lib/pymodules/python2.7/rabbitvcs/util/cajacontextmenu*.py

sudo mkdir -p /usr/lib/caja/extensions-2.0/python
sudo cp ~/Downloads/RabbitVCS.py /usr/lib/caja/extensions-2.0/python/
sudo python -m compileall /usr/lib/caja/extensions-2.0/python/RabbitVCS.py

caja -q

**Comment by bperrybap** [comment]
It worked for me on 32 bit Mint 17.1 mate  1.8.1 with caja 1.8.2 using this:
https://github.com/rabbitvcs/rabbitvcs/tree/master/clients/caja
after installing the rabbitvcs nautilus3 package.
I had it working already with nautilus 3 so I didn't try it with just instlling rabbitvcs core.

**Comment by CloCkWeRX** [comment]
Not enough to go on here re error messages, and given some folks do have it working, I'm going to close it off/recommend reports are raised for your distro

**Comment by bperrybap** [comment]
While I do agree that this is something that should be taken up by the linux mint repo,
(currently Mint 17.1 includes client support for nemo but not caja)
however, from my perspective it does seem a bit odd/inconsistent to me to have the client extensions for caja, and nemo yet not provide packages for them given that there are deb packages for Nautilus3, Nautilus2, & Thunar.

The issue I had with the way things are now, was finding client area in the git area. since it wasn't obvious to me to think to look there.
In other words, people, particularly linux mint users, are not necessarily going to think to look in the github tree to find support for their linux mint file managers (caja, nemo). If caja and nemo aren't going to get the level of support that the other filemanagers get, then it would be helpful if users could get some assistance in steering them to the client extensions in the repo rather than just being left on their own to discover them.

Maybe some kind of special note to caja & nemo linux mint users under the Ubuntu installation instructions here: http://wiki.rabbitvcs.org/wiki/install/ubuntu  that points them to the client section of the git repo.

Given the popularity of linux mint, it is likely that this type of caja support issue will be raised/bugged again, until the Mint mate edition finally pulls the caja client into the repo.

**Comment by detly** [comment]
If the Caja extension is working, it should be included as a package in our PPA. I hadn't done it yet because [the support matrix](http://wiki.rabbitvcs.org/wiki/support/matrix) lists it as stalled. If it actually works (or should work), I can create packages for it, so feel free to reopen this and assign to me.

**Comment by bperrybap** [comment]
The caja client seems to be working for me on my Mint 17.1 32 bit mate system.
I wanted to create an issue for the Mint guys since they have a nemo extension in the mint 17.1 repo but not the caja extension.
Not quite sure the best place to post an issue so I added an issue about missing caja extensions to the mate-desktop: 
https://github.com/mate-desktop/caja-extensions/issues/14

**Comment by bperrybap** [comment]
I just installed this
https://github.com/rabbitvcs/rabbitvcs/tree/master/clients/caja
on latest Linux mint  64 bit 17.3 and it seems to be work just fine.

**Comment by kimcosmos** [comment]
I get install error that python2-caja package dependency  is not listed in the repo from Bauh AUR and pamac. Python-caja is now version 3 and backwards compatible with 2, so 2 has been removed from the repo. It seems like the dependency needs to be renamed, perhaps in the source as well as the package. I don't know how to do that
