### ISSUE TITLE
RabbitVCS for Nautilus3 doesn't prompt for password on git pull/push/etc...

### ISSUE THREAD

**Issue by natinusala** [rabbitvcs/rabbitvcs#95]
Hello,

When I try to push or pull using RabbitVCS's Nautilus3 extension, I don't get prompted for my password so I get this error :

could not read Password for 'https://natinusala@bitbucket.org': No such device or address

But if I edit the repo URL and add my password in it (like https://natinusala:password@bitbucket.org/natinusala/repo.git) it works.

I've installed it using apt-get and the PPA you provide on your website.

**Comment by mondjunge** [comment]
also does not on the nemo extension. I work around this issue the same way you do.

**Comment by jesponde** [comment]
Here is a workaround for this.
The idea is to use the git-credential-gnome-keyring helper to store your credentials in gnome keyring.
The first time you will enter your credential on a git clone/push/pull, they will be stored in gnome keyring.
Since then, git will no more ask for credentials and RabbitVCS can be used as is with a git server with authentication.

Here is the procedure to install the git helper:
$ sudo apt-get install libgnome-keyring-dev
$ cd /usr/share/doc/git/contrib/credential/gnome-keyring
$ sudo make
$ git config --global credential.helper /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring

**Comment by Jens14L** [comment]
Will the pull/push issue be fixed, please? ;-)

**Comment by jesponde** [comment]
FYI, another workaround is to access Git by using SSH protocol.
In that case, credentials will no more be required, authentication and encryption will be based on your SSH public/private keys.

**Comment by monnerat** [comment]
Problem should be fixed by commit https://github.com/rabbitvcs/rabbitvcs/commit/493c78848759525103bfacf5d31e2d62d72ba7d3. If it persists, please reopen this issue. Thanks.
